config/routes.rb
Rails.application.routes.draw do
  root 'users#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  # get 'newdeposit' => 'deposit#new', as: 'newdeposit'
  # patch 'closeBankDay' => 'deposits#index', as: 'closeBankDay'

  resources :deposits
  resources :users do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  validates :sumOfDeposit, numericality: { message: "Сумма должна быть числом" }
  validates :percent, numericality: { only_integer: true, less_than_or_equal_to: 25, message: "Процент по депозиту не может быть более двадцати пяти процентов" }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  #presence - автоматический вызов
  validates :title, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord

  validates :surname, format: { with: /[А-Яа-я]/,
    message: "Введите фамилию" }, length: {minimum: 2, too_short: "Слишком короткая фамилия, введите занаво"}
  validates :name, format: { with: /[А-Яа-я]/,
    message: "Введите имя" }, length: {minimum: 2, too_short: "Слишком короткое имя, введите занаво"}
  validates :secondname, format: { with: /[А-Яа-я]/,
    message: "Введите отчество" }, length: {minimum: 2, too_short: "Слишком короткое отчество, введите занаво"}
  validates :borndate, presence: { message: "Введите дату рождения" }
  validates :sex, presence: { message: "Выберите ваш пол" }
  validates :passportserial, presence: { message: "Введите серию пасспорта" }
  validates :passportnum, presence: { message: "Введите номер пасспорта" }, uniqueness: { message: "Номер пасспорта должен быть уникальным" }
  validates :issuebody, presence: { message: "Введите орган выдачи пасспорта" }
  validates :dateissue, presence: { message: "Введите дату выдачи пасспорта" }
  validates :identnum, presence: { message: "Введите идентификационный номер" }, length: {is: 14, wrong_length: "Идентификационный номер состоит из 14 символов"}, uniqueness: { message: "Идентификационный номер должен быть уникальным" }
  validates :bornissue, presence: { message: "Введите место рождения" }
  validates :factcity, presence: { message: "Введите фактический город проживания" }
  validates :factadress, presence: { message: "Введите фактический адрес проживания" }
  validates :homephone, length: { is: 7, wrong_length: "Домашний телефон состоит из 7 цифр"}
  validates :phone, length: { minimum: 7, maximum: 13, too_short: "Слишком короткий мобильный телефон", too_long: "Слишком длинный мобильный телефон"}
  # validates :email, acceptance: { true, message: "" }
  validates :regaddress, presence: { message: "Введите адрес регистрации" }
  validates :materialstatus, presence: { message: "Введите семейное положение" }
  validates :citizenship, presence: { message: "Введите гражданство" }
  validates :disability, presence: { message: "Введите группу инвалидности, или ее отсутствие" }
  # validates :pensioner, presence: { true, message: "Введите" }
  validates :monthincome, numericality: { message: "Введите доход в цифрах" }
end
# <div class="alert alert-danger">Дата выдачи пасспорта не может быть меньше чем дата рождения!</div>

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #http_basic_authenticate_with name: 'admin', password: '12345'

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController

  def index
    @heading = 'Все депозиты'
    @deposit = Deposit.order(:depositUser).all
  end

  def new
    @heading = 'Создание депозита'
    @deposit = Deposit.new
    @user = User.order(:surname).all
  end

  def show
    @deposit = Deposit.find(params[:id]) # id по умолчанию
  end

  def update
    @deposit = Deposit.find(params[:id])
    # @deposit.percentSum = 0

    @deposit.update(:percentSum => 0.0)
    redirect_to @deposit
  end

  def destroy
    @deposit = Deposit.find(params[:id])

    @deposit.destroy
    redirect_to deposits_path
  end

  def closeBankDay
    @deposit = Deposit.all
    # @deposit.percentSum = 0

    @deposit.each do |deposit|
      deposit.update(:percentSum => 1.0)
    end
    redirect_to @deposit
  end

  def create
    # render plain: params[:user].inspect # Проверка работоспособности передачи параметров
    @deposit = Deposit.new(deposit_params)


    # Сохранение поста в БД SQLite
    if(@deposit.save)
      # Вызов метода show
      redirect_to @deposit
    else
      render 'new'
    end
  end


# Какие именно поля разрешены для передачи
  private def deposit_params
    params.require(:deposit).permit(:depositUser, :typeOfDeposit, :typeOfCurrency, :sumOfDeposit, :percent, :percentSum)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @text = 'Банковский день успешно закрыт!'
    @deposit = Deposit.all
    # @deposit.percentSum = 0

    @deposit.each do |deposit|
      sum = (deposit.sumOfDeposit + deposit.percentSum) * (deposit.percent.to_f / 100.0)
      sum += deposit.percentSum
      deposit.update(:percentSum => sum)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: '12345',
  except: [:index, :show]

  def index
    @heading = 'Все пользователи'
    @post = Post.all
  end

  def new
    @heading = 'Добавление пользователя'
    @post = Post.new
  end

  # Отправка пользователя на страницу post
  def show
    @post = Post.find(params[:id]) # id по умолчанию
  end

  #Редактирование поста
  def edit
    @heading = 'Изменение пользователя'
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end

  def create
    # render plain: params[:post].inspect # Проверка работоспособности передачи параметров
    @post = Post.new(post_params)
    # Сохранение поста в БД SQLite
    if(@post.save)
      # Вызов метода show
      redirect_to @post
    else
      render 'new'
    end
  end

# Какие именно поля разрешены для передачи
  private def post_params
    params.require(:post).permit(:surname, :name, :secondname)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: '12345',
  except: [:index, :show]

  def index
    @heading = 'Все пользователи'
    @user = User.order(:surname).all
  end

  def new
    @heading = 'Добавление пользователя'
    @user = User.new
  end

  # Отправка пользователя на страницу User
  def show
    @user = User.find(params[:id]) # id по умолчанию
  end

  #Редактирование поста
  def edit
    @heading = 'Изменение пользователя'
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if(@user.update(user_params))
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])

    @user.destroy
    redirect_to users_path
  end

  def create
    # render plain: params[:user].inspect # Проверка работоспособности передачи параметров
    @user = User.new(user_params)
    # Сохранение поста в БД SQLite
    if(@user.save)
      # Вызов метода show
      redirect_to @user
    else
      render 'new'
    end
  end


# Какие именно поля разрешены для передачи
  private def user_params
    params.require(:user).permit(:surname, :name, :secondname, :borndate, :sex, :passportserial,
        :passportnum, :issuebody, :dateissue, :identnum, :bornissue, :factcity,
        :factadress, :homephone, :phone, :email, :regaddress, :materialstatus,
        :citizenship, :disability, :pensioner, :monthincome)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/deposit_helper.rb
module DepositHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/deposits/index.html.erb
<h1><%= @heading %></h1>
<% @deposit.each do |deposit| %>
  <div class="alert alert-light">
    <h3><%= deposit.depositUser %></h3>
    <p><%= deposit.sumOfDeposit.to_i %></p>
    <%= link_to 'Просмотреть депозит', deposit_path(deposit), :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/deposits/new.html.erb
<h3><%= @heading %></h3>
<p> </p>
<%= form_for :deposit, url: deposits_path do |f| %>
  <% if @deposit.errors.any? %>
    <% @deposit.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
    <% @user = User.order(:surname).all %>
  <% end %>
  <p>
    <% fio_array = @user.map { |user| [user.surname + ' ' + user.name + ' ' + user.secondname, user.surname + ' ' + user.name + ' ' + user.secondname] } %>
    <%= f.select(:depositUser, fio_array, {:class => 'form-control'}) %>
  </p>
  <p>
    Тип депозита<br>
    <%= f.select(:typeOfDeposit, raw('<option value="Отзывной">Отзывной</option>
        <option value="Безотзывной">Безотзывной</option>
      '), {:class => 'form-control'}) %>
  </p>
  <p>
    Валюта<br>
    <%= f.select(:typeOfCurrency, raw('<option value="BYN">Белорусский рубль BYN</option>
        <option value="RUB">Русский рубль RUB</option>
        <option value="USD">Доллар $</option>
        <option value="EUR">Евро €</option>
      '), {:class => 'form-control'}) %>
  </p>
  <p>
    Сумма депозита<br>
    <%= f.text_field(:sumOfDeposit, {:class => 'form-control'}) %>
  </p>
  <p>
    Процент по депозиту<br>
    <%= f.text_field(:percent, {:class => 'form-control'}) %>
  </p>
  <%= f.check_box(:percentSum, {:class => 'd-none'}) %>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/deposits/show.html.erb
<p><%= @deposit.depositUser %></p>
<p><%= @deposit.typeOfDeposit %></p>
<p><%= @deposit.typeOfCurrency %></p>
<p><%= @deposit.sumOfDeposit %></p>
<p><%= @deposit.percent %></p>
<p><%= @deposit.percentSum %></p>
<hr>
<% if(@deposit.typeOfDeposit == "Отзывной") %>
  <%= button_to 'Снять проценты', deposit_path(@deposit),
  method: :patch,
  data: {confirm: 'Вы уверены?'},
  :class => 'btn btn-warning' %>
  <hr>
<% end %>
<%= link_to 'Закрыть депозит', deposit_path(@deposit),
method: :delete,
data: {confirm: 'Вы уверены?'},
:class => 'btn btn-danger' %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Банковская система</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-bold">Учет пользователей банка</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark"><%= link_to 'Клиенты', home_path %></span>
        <span class="p-2 text-dark"><%= link_to 'Депозиты', deposits_path %></span>
      </nav>
      <span class="p-2 text-dark" ><%= link_to 'Добавить пользователя', new_user_path %></span>
      <span class="p-2 text-dark" ><%= link_to 'Создать депозит', new_deposit_path %></span>
      <span class="p-2 text-dark" ><%= link_to 'Закрытие банковского дня', about_path, data: {confirm: 'Вы уверены?'} %></span>
    </div>

    <div class="container"
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @text %></h1>
<hr>
<%= link_to 'Перейти к списку клиентов', home_path, :class => 'btn btn-outline-info'  %>
<%= link_to 'Перейти к списку депозитов', deposits_path, :class => 'btn btn-outline-secondary'  %>

app/views/posts/edit.html.erb
<h3><%= @heading %></h3>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Name<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Article text<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1><%= @heading %></h1>
<% @post.each do |post| %>
  <div class="alert alert-light">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to 'Read article', post_path(post), :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h3><%= @heading %></h3>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Фамилия<br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    Имя<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>

  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to 'Edit article', edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to 'Delete article', post_path(@post),
method: :delete,
data: {confirm: 'Are you sure?'},
:class => 'btn btn-danger' %>
<hr>
<h3>All comments</h3>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
  </div>
<% end %>
<hr>
<h3>Add comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    User<br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>
  <p>
    Comment text<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit('Add comment', {:class => 'btn btn-warning'}) %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h3><%= @heading %></h3>
<p> </p>
<%= form_for :user, url: user_path(@user), method: :patch do |f| %>

  <p>
    Фамилия<br>
    <%= f.text_field(:surname, {:class => 'form-control'}) %>
  </p>
  <p>
    Имя<br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>
  <p>
    Отчество<br>
    <%= f.text_field(:secondname, {:class => 'form-control'}) %>
  </p>
  <p>
    Дата рождения<br>
    <%= date1 = f.date_field :borndate, max: Date.today, :class => 'form-control' %>
  </p>
  <p>
    Пол<br>
    М<%= f.radio_button(:sex, "М", {:class => 'btn btn-success'}) %>
    Ж<%= f.radio_button(:sex, "Ж", {:class => 'btn btn-success'}) %>
  </p>
  <p>
    Серия паспорта<br>
    <%= f.text_field(:passportserial, {:class => 'form-control'}) %>
  </p>
  <p>
    № паспорта<br>
    <%= f.text_field(:passportnum, {:class => 'form-control'}) %>
  </p>
  <p>
    Кем выдан<br>
    <%= f.text_field(:issuebody, {:class => 'form-control'}) %>
  </p>
  <p>
    Дата выдачи<br>
    <%= date2 = f.date_field :dateissue, max: Date.today, :class => 'form-control' %>
  </p>
  <p>
    Идентификационный номер<br>
    <%= f.text_field(:identnum, {:class => 'form-control'}) %>
  </p>
  <p>
    Место рождения<br>
    <%= f.text_field(:bornissue, {:class => 'form-control'}) %>
  </p>
  <p>
    Город фактического проживания<br>
    <%= f.select(:factcity, raw('<option value="Брест">Брест</option>
        <option value="Витебск">Витебск</option>
        <option value="Гомель">Гомель</option>
        <option value="Гродно">Гродно</option>
        <option value="Минск">Минск</option>
        <option value="Могилев">Могилев</option>
      '), {:class => 'form-control'}) %>
  </p>
  <p>
    Адрес фактического проживания<br>
    <%= f.text_field(:factadress, {:class => 'form-control'}) %>
  </p>
  <p>
    Телефон домашний<br>
    <%= f.text_field(:homephone, {:class => 'form-control'}) %>
  </p>
  <p>
    Телефон мобильный<br>
    <%= f.text_field(:phone, {:class => 'form-control'}) %>
  </p>
  <p>
    Email<br>
    <%= f.text_field(:email, {:class => 'form-control'}) %>
  </p>
  <p>
    Адрес прописки<br>
    <%= f.text_field(:regaddress, {:class => 'form-control'}) %>
  </p>
  <p>
    Семейное положение<br>
    <%= f.select(:materialstatus, raw('<option value="Не замужем(Не женат)">Не замужем(Не женат)</option>
        <option value="Замужем(Женат)">Замужем(Женат)</option>
        <option value="Разведен(а)">Разведен(а)</option>
        <option value="Вдова(Вдовец)">Вдова(Вдовец)</option>
      '), {:class => 'form-control'}) %>
  </p>
  <p>
    Гражданство<br>
    <%= f.select(:citizenship, raw('<option value="Белорусское">Белорусское</option>
        <option value="Русское">Русское</option>
        <option value="Польское">Польское</option>
        <option value="Литовское">Литовское</option>
        <option value="Украинское">Украинское</option>
        <option value="Латвийское">Латвийское</option>
        <option value="Иное">Иное</option>
      '), {:class => 'form-control'}) %>
  </p>
  <p>
    Инвалидность<br>
    <%= f.select(:disability, raw('<option value="Нету">Нету</option>
        <option value="1-ой степени">1-ой степени</option>
        <option value="2-ой степени">2-ой степени</option>
        <option value="3-ой степени">3-ой степени</option>
        <option value="4-ой степени">4-ой степени</option>
      '), {:class => 'form-control'}) %>
  </p>
  <p>
    Пенсионер<br>
    <%= f.check_box(:pensioner, {:class => 'btn btn-success'}) %>
  </p>
  <p>
    Ежемесячный доход<br>
    <%= f.text_field(:monthincome, {:class => 'form-control'}) %>
  </p>
  <% if date2 < date1 %>
  <% @user.errors.add(:dateissue, "Дата выдачи пасспорта не может быть меньше чем дата рождения") %>
  <% end %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/users/index.html.erb
<h1><%= @heading %></h1>
<% @user.each do |user| %>
  <div class="alert alert-light">
    <h3><%= user.surname %></h3>
    <p><%= user.name %></p>
    <%= link_to 'Просмотреть пользователя', user_path(user), :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1><%= @heading %></h1>
<p> </p>
<%= form_for :user, url: users_path do |f| %>

  <p>
    Фамилия<br>
    <%= f.text_field(:surname, {:class => 'form-control'}) %>
  </p>
  <p>
    Имя<br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>
  <p>
    Отчество<br>
    <%= f.text_field(:secondname, {:class => 'form-control'}) %>
  </p>
  <p>
    Дата рождения<br>
    <%= date1 = f.date_field :borndate, max: Date.today, :class => 'form-control' %>
  </p>
  <p>
    Пол<br>
    М<%= f.radio_button(:sex, "М", {:class => 'btn btn-success'}) %>
    Ж<%= f.radio_button(:sex, "Ж", {:class => 'btn btn-success'}) %>
  </p>
  <p>
    Серия паспорта<br>
    <%= f.text_field(:passportserial, {:class => 'form-control'}) %>
  </p>
  <p>
    № паспорта<br>
    <%= f.text_field(:passportnum, {:class => 'form-control'}) %>
  </p>
  <p>
    Кем выдан<br>
    <%= f.text_field(:issuebody, {:class => 'form-control'}) %>
  </p>
  <p>
    Дата выдачи<br>
    <%= date2 = f.date_field :dateissue, max: Date.today, :class => 'form-control' %>
  </p>
  <p>
    Идентификационный номер<br>
    <%= f.text_field(:identnum, {:class => 'form-control'}) %>
  </p>
  <p>
    Место рождения<br>
    <%= f.text_field(:bornissue, {:class => 'form-control'}) %>
  </p>
  <p>
    Город фактического проживания<br>
    <%= f.select(:factcity, raw('<option value="Брест">Брест</option>
        <option value="Витебск">Витебск</option>
        <option value="Гомель">Гомель</option>
        <option value="Гродно">Гродно</option>
        <option value="Минск">Минск</option>
        <option value="Могилев">Могилев</option>
      '), {:class => 'form-control'}) %>
  </p>
  <p>
    Адрес фактического проживания<br>
    <%= f.text_field(:factadress, {:class => 'form-control'}) %>
  </p>
  <p>
    Телефон домашний<br>
    <%= f.text_field(:homephone, {:class => 'form-control'}) %>
  </p>
  <p>
    Телефон мобильный<br>
    <%= f.text_field(:phone, {:class => 'form-control'}) %>
  </p>
  <p>
    Email<br>
    <%= f.text_field(:email, {:class => 'form-control'}) %>
  </p>
  <p>
    Адрес прописки<br>
    <%= f.text_field(:regaddress, {:class => 'form-control'}) %>
  </p>
  <p>
    Семейное положение<br>
    <%= f.select(:materialstatus, raw('<option value="Не замужем(Не женат)">Не замужем(Не женат)</option>
        <option value="Замужем(Женат)">Замужем(Женат)</option>
        <option value="Разведен(а)">Разведен(а)</option>
        <option value="Вдова(Вдовец)">Вдова(Вдовец)</option>
      '), {:class => 'form-control'}) %>
  </p>
  <p>
    Гражданство<br>
    <%= f.select(:citizenship, raw('<option value="Белорусское">Белорусское</option>
        <option value="Русское">Русское</option>
        <option value="Польское">Польское</option>
        <option value="Литовское">Литовское</option>
        <option value="Украинское">Украинское</option>
        <option value="Латвийское">Латвийское</option>
        <option value="Иное">Иное</option>
      '), {:class => 'form-control'}) %>
  </p>
  <p>
    Инвалидность<br>
    <%= f.select(:disability, raw('<option value="Нету">Нет</option>
        <option value="1-ой степени">1-ой степени</option>
        <option value="2-ой степени">2-ой степени</option>
        <option value="3-ой степени">3-ой степени</option>
        <option value="4-ой степени">4-ой степени</option>
      '), {:class => 'form-control'}) %>
  </p>
  <p>
    Пенсионер<br>
    <%= f.check_box(:pensioner, {:class => 'btn btn-success'}) %>
  </p>
  <p>
    Ежемесячный доход<br>
    <%= f.text_field(:monthincome, {:class => 'form-control'}) %>
  </p>
  <% if date2 < date1 %>
  <% @user.errors.add(:dateissue, "Дата выдачи пасспорта не может быть меньше, чем дата рождения") %>
  <% end %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.submit({:class => 'btn btn-success'}) %>
  </p>
<% end %>

app/views/users/show.html.erb
<p><%= @user.surname %></p>
<p><%= @user.name %></p>
<p><%= @user.secondname %></p>
<p><%= @user.borndate %></p>
<%= sex = "" %>
<% if @user.sex then %>
<% sex = "Мужчина" %>
<% else %>
<% sex = "Женщина" %>
<% end %>
<p><%= sex %></p>
<p><%= @user.passportserial %></p>
<p><%= @user.passportnum %></p>
<p><%= @user.issuebody %></p>
<p><%= @user.dateissue %></p>
<p><%= @user.identnum %></p>
<p><%= @user.bornissue %></p>
<p><%= @user.factcity %></p>
<p><%= @user.factadress %></p>
<p><%= @user.homephone %></p>
<p><%= @user.phone %></p>
<p><%= @user.email %></p>
<p><%= @user.regaddress %></p>
<p><%= @user.materialstatus %></p>
<p><%= @user.citizenship %></p>
<p><%= @user.disability %></p>
<%= pensioner = "" %>
<% if @user.pensioner then %>
<% pensioner = "Пенсионер" %>
<% else %>
<% pensioner = "Не пенсионер" %>
<% end %>
<p><%= pensioner %></p>
<p><%= @user.monthincome %></p>
<hr>
<%= link_to 'Изменить пользователя', edit_user_path(@user), :class => 'btn btn-warning' %>
<%= link_to 'Удалить пользователя', user_path(@user),
method: :delete,
data: {confirm: 'Вы уверены?'},
:class => 'btn btn-danger' %>
<hr>